FF-156: Base withdrawal api
rbkmoney/fistful-server pull request #284
Opened 2020-08-26 09:31 UTC by WWWcool

2020-08-26 19:22 UTC, ciiol requested changes
👍

2020-08-26 19:22 UTC, ciiol commented on apps/wapi/src/wapi_withdrawal_backend.erl
> +    when WithdrawalError ::
А может это просто в отдельный тип убрать?

2020-08-26 19:22 UTC, ciiol commented on apps/wapi/src/wapi_withdrawal_backend.erl
> +            {error, {identity, notfound}};
Кстати, вроде эта ошикба не соответсвует типу в функции выше. И те ошибки, что ниже, тоже.

2020-08-26 19:22 UTC, ciiol commented on apps/wapi/src/wapi_withdrawal_backend.erl
> +    {ok, undefined}.
А почему не просто `ok`?

2020-08-26 19:22 UTC, ciiol commented on apps/wapi/src/wapi_withdrawal_backend.erl
> +    {error, {quote, {invalid_withdrawal, DestinationID}}}.
А не
```suggestion
    {error, {quote, {invalid_destination, DestinationID}}}.
```
?

2020-08-26 19:22 UTC, ciiol commented on apps/wapi/src/wapi_withdrawal_backend.erl
> +    {error, {quote, {invalid_withdrawal, DestinationID}}}.
Это, кстати, говорит о том, что, видимо, не хватает тестов.

2020-08-26 21:10 UTC, WWWcool commented on apps/wapi/src/wapi_withdrawal_backend.erl
> +    {error, {quote, {invalid_withdrawal, DestinationID}}}.
да тестов там мало - только хепи кейсы в основном

2020-08-26 21:10 UTC, WWWcool commented on apps/wapi/src/wapi_withdrawal_backend.erl
> +    {ok, undefined}.
там неудобно дальше матчить тогда

2020-08-26 21:10 UTC, WWWcool commented on apps/wapi/src/wapi_withdrawal_backend.erl
> +            {error, {identity, notfound}};
да, нужно прошерстить хорошенько тот тип что сверху - думаю как раз он не правильный

2020-08-28 07:52 UTC, ciiol commented on apps/wapi/src/wapi_wallet_thrift_handler.erl
> -        {error, {wallet, {inaccessible, _}}} ->
Хм, по идее, ошибка `inaccessible` должна возникать. Если, например, кошелек или пати заблокирована.

2020-08-28 07:59 UTC, WWWcool commented on apps/wapi/src/wapi_wallet_thrift_handler.erl
> -        {error, {wallet, {inaccessible, _}}} ->
в фистфульном типе ее нет, если только на стороне вапи она возникала

2020-08-28 08:14 UTC, WWWcool commented on apps/wapi/src/wapi_wallet_thrift_handler.erl
> -        {error, {wallet, {inaccessible, _}}} ->
еще вроде как я это смотрел недавно когда прошаривал вапи и фистфул - там вроде как эта доступность сущностей не проверялась, но нужно уточнить

2020-08-28 09:46 UTC, ciiol commented on apps/wapi/src/wapi_wallet_thrift_handler.erl
> -        {error, {wallet, {inaccessible, _}}} ->
Странно, но ладно

2020-08-28 09:46 UTC, ciiol approved these changes

2020-08-31 18:53 UTC, merged