FF-217: Refactor webhook api
rbkmoney/fistful-server pull request #299
Opened 2020-09-09 07:47 UTC by 4tyTwo

2020-09-09 11:31 UTC, WWWcool requested changes

2020-09-09 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +-type result(T, E)  :: {ok, T} | {error, E}.
старались уйти от этой конструкции в сторону 
``` 
-type req_data() :: wapi_handler:req_data().
-type handler_context() :: wapi_handler:context().
-type response_data() :: wapi_handler:response_data().

-spec create(req_data(), handler_context()) ->

```

2020-09-09 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_wallet_handler.erl
> +    case wapi_webhook_backend:get_webhook(WebhookID, IdentityID, Context) of
в трифторвый хендлер это бы продублировать

2020-09-09 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +-define(CTX_NS, <<"com.rbkmoney.wapi">>).
кажется это тут не нужно

2020-09-09 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +create_webhook(Params, Context) ->
```suggestion
create_webhook(#{'Webhook' := Params}, Context) ->
```

2020-09-09 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +        {ok, {error, Error}} ->
```suggestion
        {_, {error, Error}} ->
```

2020-09-09 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +    IdentityAccessible = wapi_access_backend:check_resource_by_id(identity, IdentityID, Context),
в такой конструкции ты лишний вызов делаешь даже если предыдущий окончился неуспехом

2020-09-09 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +    NewParams = #{
```suggestion
    WebhookParams = #{
```

2020-09-09 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +    } = unmarshal(webhook_params, maps:get('Webhook', Params)),
здесь должен быть маршалинг из свага сразу в трифт, чтобы ниже не перекладывать из мапы в трифт

2020-09-09 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +            {error, {identity, Error}} % TODO
забытое?

2020-09-09 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +get_webhook(WebhookID, IdentityID, Context) ->
```suggestion
get_webhook(WebhookID, IdentityID, HandlerContext) ->
```
так как в старом варианте всегда была путанница из за вложенной структуры этого контекста

2020-09-09 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +
может не стоит между клаусами одной функции вставлять пустые строки

2020-09-09 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +%% marshaling
кажется в других модулях marshal = swag -> thrift  VS unmarshal = thrift -> swag

2020-09-09 11:41 UTC, 4tyTwo commented on apps/wapi/src/wapi_webhook_backend.erl
> +    IdentityAccessible = wapi_access_backend:check_resource_by_id(identity, IdentityID, Context),
Ну да, либо лишний вызов либо еще один уровень вложенности, выбрал первое, но и второе, наверное, нормальн

2020-09-09 11:52 UTC, 4tyTwo commented on apps/wapi/src/wapi_wallet_handler.erl
> +    case wapi_webhook_backend:get_webhook(WebhookID, IdentityID, Context) of
А он есть?

2020-09-09 12:03 UTC, 4tyTwo commented on apps/wapi/src/wapi_webhook_backend.erl
> +            {error, {identity, Error}} % TODO
Забыл удалить 😓

2020-09-09 20:41 UTC, WWWcool commented on apps/wapi/src/wapi_wallet_handler.erl
> +    case wapi_webhook_backend:get_webhook(WebhookID, IdentityID, Context) of
wapi_wallet_thrift_handler

2020-09-09 20:42 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +    IdentityAccessible = wapi_access_backend:check_resource_by_id(identity, IdentityID, Context),
вложенность это только отображение в коде, а последовательность исполнение это уже логика программы - жертвовать логикой из-за внешнего вида - такое себе)

2020-09-09 20:42 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +    IdentityAccessible = wapi_access_backend:check_resource_by_id(identity, IdentityID, Context),
ты можешь сделать еще одну функцию как я делал в других чтобы уровень вложенности не зашкаливал в одной

2020-09-09 20:44 UTC, WWWcool commented
Хочу напомнить, что резолвы сделаны для того кто ревьюит, а не того кого ревьюят, чтобы можно было зарезолвить тот коммент, который ты считаешь что уже пофикисли, а то может я все еще считаю что что то не решено, а ты зарезолвил)

2020-09-09 20:45 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +get_webhook(WebhookID, IdentityID, Context) ->
Например тут я предлагал во всем файле это поправить, но коммент был про одно место

2020-09-09 20:50 UTC, WWWcool commented
еще бы я предложил по возможности уходить от сквозной функции маршал/анмаршал в сторону частных - например wapi_withdrawal_backend:unmarshal_body -- суть ухода в том, чтобы можно было более строго типизировать эти функции при необходимости

2020-09-11 09:24 UTC, WWWcool reviewed
Пара миноров осталась

2020-09-11 09:24 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +                    {error, {identity, notfound}};
кажется не та ошибка

2020-09-11 09:24 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
>      ok;
странный кейс, ты либо получаешь ответ либо ошибку, а тут какой-то неопределенный вариант

2020-09-11 09:24 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
>  unmarshal(webhook_event_types, {withdrawal, EventType}) ->
шел шел шел и сломался? не понял почему именно здесь решил, что хватит индивидуального маршалинга и можно уже оставить старый. Если брать мои модули, то я руководствовался такой идеей - если есть что-то что можно переиспользовать из ff_codec, то оставлял его и сквозную, если нельзя - писал локальный.

2020-09-11 11:27 UTC, 4tyTwo commented on apps/wapi/src/wapi_webhook_backend.erl
>      ok;
так там ответ на void операцию, возвращаем ok и все

2020-09-11 12:05 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
>      ok;
аа. понял - теперь я не уверен что процессить все ответы одной функций самая хорошая идея, так как при чтении кода приходится дополнительно рыть куда какой клаус относится, может это переделать?

2020-09-14 09:45 UTC, 4tyTwo commented on apps/wapi/src/wapi_webhook_backend.erl
>      ok;
Согласен что не идеально очевидно, но мне нормально. Единственный вариант, что вижу, написать отдельные функции типа `handle_create_webhook_result` (название приблизительное) под каждую операцию, это больше кода, но мб лучше читается

2020-09-14 11:31 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
>      ok;
давай хотя бе тег добавим первым аргументом - тип - 
```
process_result(delete, {ok, _}) ->
    ok;
```

2020-09-14 11:59 UTC, 4tyTwo commented on apps/wapi/src/wapi_webhook_backend.erl
>      ok;
Тег первым аргументом мне если честно не нравится, это будет несколько запутанно и болезненно напоминать маршалинг, который я только что переписывал. Если ты не против, пойду по пути отдельных функций

2020-09-15 09:20 UTC, WWWcool approved these changes

2020-09-15 09:20 UTC, WWWcool commented on apps/wapi/src/wapi_webhook_backend.erl
> +
строчка лишняя

2020-09-15 09:22 UTC, merged