FF-218: p2p transfer via thrift
rbkmoney/fistful-server pull request #301
Opened 2020-09-11 07:05 UTC by aenglisc

2020-09-11 09:10 UTC, WWWcool requested changes
еще бы я предложил по возможности уходить от сквозной функции маршал/анмаршал в сторону частных - например wapi_withdrawal_backend:unmarshal_body -- суть ухода в том, чтобы можно было более строго типизировать эти функции при необходимости

2020-09-11 09:10 UTC, WWWcool commented on apps/wapi/src/wapi_wallet_thrift_handler.erl
> +process_request('CreateP2PTransfer', #{'P2PTransferParameters' := Params}, Context, _Opts) ->
выглядит будто ошибок тут намного больше чем по факту из функции возвращается

2020-09-11 09:10 UTC, WWWcool commented on apps/wapi/test/wapi_wallet_dummy_data.hrl
> +
а мок тестов то не допилил - у тебя еще макрос так ошибку выдаст - нужно чтобы все используемые макросы были раньше объявлены

2020-09-11 12:47 UTC, aenglisc commented on apps/ff_cth/src/ct_payment_system.erl
> +                ]},
Не решил, он собственно и использовался.

2020-09-11 19:30 UTC, WWWcool commented on apps/ff_cth/src/ct_payment_system.erl
> +                ]},
там скорее всего провайдера нужно было другого указать, тогда бы он другой PaymentInstitution выбрал, в котором есть этот конфиг

2020-09-14 06:59 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
> +            {error, {terms, {terms_violation, cash_range}}};
прошлый вариант был лучше

2020-09-14 06:59 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
>  }) ->
может все-таки внести это под один клаус?

2020-09-14 06:59 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
> +unmarshal_receiver({resource, #p2p_transfer_RawResource{
и тут

2020-09-14 06:59 UTC, WWWcool commented on apps/wapi/test/wapi_p2p_transfer_tests_SUITE.erl
> +        {[p2p], write}
эти штуки уже не влияют когда есть пати - пати все открывает

2020-09-14 06:59 UTC, WWWcool commented on apps/wapi/test/wapi_p2p_transfer_tests_SUITE.erl
> +    ], C).
В тестах неудобно смотреть в эту функцию, чтобы из нее отреверсить что будет сделано, экономить тут строчки не прямо обязательная задачка, поэтому я бы предложил по месту все инструкции вставлять

2020-09-14 07:20 UTC, aenglisc commented on apps/wapi/test/wapi_p2p_transfer_tests_SUITE.erl
> +    ], C).
Линтер ругается :(

2020-09-14 07:22 UTC, aenglisc commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
>  }) ->
Они не изоморфны же

2020-09-14 07:23 UTC, aenglisc commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
> +            {error, {terms, {terms_violation, cash_range}}};
Хотелось сделать ближе к тому, что в самом фистфуле.

2020-09-14 08:04 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
> +            {error, {terms, {terms_violation, cash_range}}};
смысла нет, фистфул уже не имеет отношения к этому коду уже - все через трифт будет

2020-09-14 08:10 UTC, WWWcool commented on apps/wapi/test/wapi_p2p_transfer_tests_SUITE.erl
> +    ], C).
а у него тесты не в исключениях чтоль? ((

2020-09-14 08:16 UTC, WWWcool commented
Да, котировки как входного аргумента для создания трансфера не хватает, так что нужно допилить - еще предлагаю посмотреть мельком на стороне фистфула как там все разжимается - а то там тоже спецэффекты бывают

2020-09-14 08:18 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
>  }) ->
ок, просто достаточно объемный кусок копипасты выходит, когда по факту отличий у них еще нет, может быть оставить такой рефактор до того момента когда появятся настоящие отличия?

2020-09-14 08:38 UTC, aenglisc commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
>  }) ->
Как минимум в сваговом типе и наличии контактных данных.

2020-09-14 08:39 UTC, aenglisc commented on apps/wapi/test/wapi_p2p_transfer_tests_SUITE.erl
> +    ], C).
Тесты ж тоже должны каким-то нормам соответствовать.

2020-09-14 08:46 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
>  }) ->
ок ок) оставляем тогда так, убедил

2020-09-14 08:47 UTC, WWWcool commented on apps/wapi/test/wapi_p2p_transfer_tests_SUITE.erl
> +    ], C).
слушай, а у тебя ошибка в этих моках - {fistful_identity, fun('Get', _) -> {ok, ?IDENTITY(PartyID)} end},
        {fistful_identity, fun('GetContext', _) -> {ok, ?DEFAULT_CONTEXT(ContextPartyID)} end}, так не будет работать - нужно их под один тег занести

2020-09-14 08:51 UTC, aenglisc commented on apps/wapi/test/wapi_p2p_transfer_tests_SUITE.erl
> +    ], C).
Под тегом ты что имеешь в виду?

2020-09-14 09:16 UTC, WWWcool commented on apps/wapi/test/wapi_p2p_transfer_tests_SUITE.erl
> +    ], C).
Пример из кошелька
```
{fistful_wallet,
            fun
                ('GetContext', _) -> {ok, ?DEFAULT_CONTEXT(PartyID)};
                ('GetAccountBalance', _) -> {ok, ?ACCOUNT_BALANCE}
            end
        }
```

2020-09-15 09:13 UTC, WWWcool reviewed
я бы еще докинул в интеграционный тест котировку - там тогда должен всплыть тот баг, о котором Ваня писал

2020-09-15 09:13 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_quote.erl
> +    quote().
наученный)

2020-09-15 09:13 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
> +        TransferParams = marshal_transfer_params(Params#{<<"id">> => ID}),
может это вынести в отдельную функцию, чтобы не пихать сюда эти детали работы с токеном и котировкой?

2020-09-15 09:13 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
> +process_p2p_transfer_call(Request, HandlerContext) ->
кажется это как раз лишняя функция

2020-09-15 09:13 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
> +    ff_pipeline:unwrap(Res).
можно было сделать инпорт как везде, не нужно эту обертку тащить

2020-09-15 09:13 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
> +        TransferParams = marshal_transfer_params(Params#{<<"id">> => ID}),
глянь еще мой ПР про выплаты - я там как раз решал такую же проблему + переделывал котировку на трифт (скорее всего уже в мастере)

2020-09-15 09:18 UTC, aenglisc commented
> я бы еще докинул в интеграционный тест котировку - там тогда должен всплыть тот баг, о котором Ваня писал

Я как раз сейчас с ним борюсь

2020-09-16 07:17 UTC, aenglisc commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
> +process_p2p_transfer_call(Request, HandlerContext) ->
Чуть перекроил, сейчас она поэлегантнее вписывается

2020-09-16 11:24 UTC, WWWcool reviewed
Надо бы котировку по аналогии с выплатной сделать - чтобы там трифт был и соответственно в тестах на нее перейти

2020-09-18 13:12 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_quote.erl
> +    }).
На мои же грабли и наступил - я в начале тоже так сделал и Андрей меня попросил допилить этот модуль чтобы он только трифт отдавал - а в тех местах где нужно другое представление по месту добавить соответствующие функции, это в текущей версии и сделано, думаю здесь нужно также сделать

2020-09-18 13:12 UTC, WWWcool commented on apps/wapi/src/wapi_access_backend.erl
> +                       | p2p_template
а это откуда тут взялось?

2020-09-18 13:12 UTC, WWWcool commented on apps/wapi/src/wapi_access_backend.erl
> +    ff_proto_p2p_template_thrift:'P2PTemplateState'().
и это?

2020-09-18 13:48 UTC, aenglisc commented on apps/wapi/src/wapi_access_backend.erl
> +                       | p2p_template
От мержа артефакты видимо

2020-09-22 15:17 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
> +     | {p2p_transfer, cash_range_exceeded}
{p2p_transfer, operation_not_permitted} тут тоже может быть

2020-09-22 15:17 UTC, WWWcool commented on apps/wapi/src/wapi_p2p_transfer_backend.erl
> +    TransferParams#p2p_transfer_P2PTransferParams{quote = Quote};
тут нужно ду добавить, а на уровень выше анврап

2020-09-22 15:17 UTC, WWWcool commented on apps/ff_cth/src/ct_payment_system.erl
> +                ]},
может указать? зачем лишние конфиги дописывать, если уже есть готовые

2020-10-06 08:40 UTC, WWWcool approved these changes

2020-10-06 08:43 UTC, merged