ED-101: party management terms calculation
rbkmoney/fistful-server pull request #385
Opened 2021-04-01 14:23 UTC by georgemadskillz

2021-04-14 22:06 UTC, georgemadskillz commented on apps/ff_cth/src/ct_domain.erl
> +            terms = #domain_ProvisionTermSet{}
Без этой фишки ломается тест provider_operations_forbidden_fail_test в ff_withdrawal_SUITE с ошибкой
``` code
{system,
{external,
result_unexpected,
<<"error:{invalid,['$reply'],undefined}">>}}.
```
В протоколе в #domain_Terminal поле 14: optional ProvisionTermSet terms является опциональным, поэтому странно, что оно так ломается. Я пытался понять, почему undefined нам ломает вызов пати менеджмента (внутри ff_payment_institution:withdrawal_providers), на стороне хеллгейта на undefined проверки есть (в pm_provider:reduce_provider).

2021-04-14 22:42 UTC, georgemadskillz commented on apps/ff_cth/src/ct_domain.erl
> +                []
Без этого падает к примеру тест create_p2p_transfer_ok_test в ff_p2p_transfer_handler_SUITE с ошибкой
``` code
{system,
{external,
 result_unexpected,
 <<"error:function_clause in pm_selector:reduce(undefined,#{cost => {domain_Cash,256, ......
```
Поле terminal в #domain_Provider опциональное, но при рачете термсов через пати-менеджмент в хеллгейте
вызывается функция pm_selector:reduce в клаусами
 ``` code
reduce({value, _} = V, _, _) ->
 ...
reduce({decisions, Ps}, VS, Rev) ->
```
и undefined домает расчет.
Тут конечно вопрос, как правильно - делать поле терминал обязательным? (Наверное еще рано, пока не перешли полностью на новый роутинг и не выпилили селекторы) или в хелллгейте проверять undefined, либо пока добавить сюда терминал c пустыми decisions, чтобы не падало. Хм.

2021-04-19 11:47 UTC, ndiezel0 requested changes

2021-04-19 11:47 UTC, ndiezel0 commented on apps/ff_cth/src/ct_domain.erl
> +                []
Так как тебе это нужно для легаси, то я бы предложить сделать PR в PartyManagement, который сделал бы это поле опциональным.

2021-04-19 11:47 UTC, ndiezel0 commented on apps/ff_cth/src/ct_domain.erl
> +            terms = #domain_ProvisionTermSet{}
Я так понимаю ты вызываешь `ComputeProviderTerminalTerms`, при этом у тебя нет terms ни в Terminal, ни в Provider. Какой смысл в такой операции я не знаю, как это обрабатывать - наверно кидать ошибку, можешь добавить как результат выполнения `ComputeProviderTerminalTerms`

2021-04-19 11:48 UTC, ndiezel0 commented on apps/ff_cth/src/ct_domain.erl
> +            terms = #domain_ProvisionTermSet{}
Под ошибкой я имею в виду бросать эрланговый эксепшн и 500ить. Иначе я не представляю как ты это в FF обработаешь.

2021-04-22 07:34 UTC, georgemadskillz commented on apps/ff_cth/src/ct_domain.erl
> +            terms = #domain_ProvisionTermSet{}
```
    domain.ProvisionTermSet ComputeProviderTerminalTerms ( 
        1: UserInfo user, 
        2: domain.ProviderRef provider_ref, 
        3: domain.TerminalRef terminal_ref,
        4: domain.DataRevision domain_revision,
        5: Varset varset\
    )
        throws (
            1: InvalidUser ex1,
            2: ProviderNotFound ex2,
            3: TerminalNotFound ex3
        )
```

В трифте для этой функции не заложен эксепшн отсутствия обоих термсов, получается нужно кидать или другой эксепшн, либо дописывать его в протокол? Не слишком ли много движений для легаси кода? Или эксепшн нужно кидать в том месте, где ломается уже на этапе возврата undefined где-то там в woody?

2021-05-12 17:05 UTC, ndiezel0 commented on apps/p2p/src/p2p_transfer_routing.erl
> +        [_Route | _] ->
Кажется эта проверка не нужна, раз мы покрыли пустой список выше.

2021-05-17 11:34 UTC, ndiezel0 commented on apps/fistful/src/ff_payment_institution.erl
> +    end.
```suggestion
    get_selector_value(p2p_inspector, P2PInspectorSelector).
```

2021-05-17 11:34 UTC, ndiezel0 commented on apps/p2p/src/p2p_transfer.erl
> +            compute_fees(ProviderFees, Body);
Название функции не соответствует ее функционалу.

2021-05-17 12:56 UTC, ndiezel0 approved these changes

2021-05-17 14:57 UTC, merged